#!/bin/bash

# Usage: cat yoursqlfile.sql | ./split-sql

read sqlfile;

mkdir -p output;

cat $sqlfile | awk -v \
    RS="-- --------------------------------------------------------" \
    'NR > 1 { \
        print RS $0 > "output/partial_sql_" (NR-1) ".sql"; \
        close("output/partial_sql_" (NR-1) ".sql") \
    }';

echo 'boom';
